# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Test
      run: go test -v ./...

    - name: Login ke Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_HUB }}
    
    - name: Build and push docker image
      uses: docker/build-push-action@v3
      with:
          push: true
          tags: cehamot/golang-apiserver:${{ github.run_number }}

  provisioning-server:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Login ke Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_HUB }}
    - name: executing remote ssh deploy container
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SSH_IP }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          docker pull cehamot/golang-apiserver:${{ github.run_number }}
          docker rm -f apiserver
          docker run --name apiserver -d -p 80:8144 cehamot/golang-apiserver:${{ github.run_number }}
